// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PW3.Emoji.Entidades.EF;

#nullable disable

namespace PW3.Emoji.Entidades.Migrations
{
    [DbContext(typeof(PW3_EmojiContext))]
    [Migration("20251103145316_InitialSetupLimpio")]
    partial class InitialSetupLimpio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.AnalisisResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confianza")
                        .HasColumnType("REAL");

                    b.Property<int>("EmocionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("ImagenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VectorJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Analisis__3214EC07E3FD976B");

                    b.HasIndex(new[] { "EmocionId" }, "IX_Analisis_EmocionId");

                    b.HasIndex(new[] { "ImagenId" }, "IX_Analisis_ImagenId");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Analisis_UsuarioId");

                    b.ToTable("AnalisisResultado", (string)null);
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Emocion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Emocion__3214EC0709188CAD");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Emocion_Nombre")
                        .IsUnique();

                    b.ToTable("Emocion", (string)null);
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Alto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ancho")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Imagen__3214EC0739CCA6A4");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Imagen_UsuarioId");

                    b.ToTable("Imagen", (string)null);
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Rol__3214EC077CE478FD");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC07EBC80A05");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuario_Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.AnalisisResultado", b =>
                {
                    b.HasOne("PW3.Emoji.Entidades.EF.Emocion", "Emocion")
                        .WithMany("AnalisisResultados")
                        .HasForeignKey("EmocionId")
                        .IsRequired()
                        .HasConstraintName("FK_Analisis_Emocion");

                    b.HasOne("PW3.Emoji.Entidades.EF.Imagen", "Imagen")
                        .WithMany("AnalisisResultados")
                        .HasForeignKey("ImagenId")
                        .IsRequired()
                        .HasConstraintName("FK_Analisis_Imagen");

                    b.HasOne("PW3.Emoji.Entidades.EF.Usuario", "Usuario")
                        .WithMany("AnalisisResultados")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Analisis_Usuario");

                    b.Navigation("Emocion");

                    b.Navigation("Imagen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Imagen", b =>
                {
                    b.HasOne("PW3.Emoji.Entidades.EF.Usuario", "Usuario")
                        .WithMany("Imagens")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Imagen_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Usuario", b =>
                {
                    b.HasOne("PW3.Emoji.Entidades.EF.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Emocion", b =>
                {
                    b.Navigation("AnalisisResultados");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Imagen", b =>
                {
                    b.Navigation("AnalisisResultados");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PW3.Emoji.Entidades.EF.Usuario", b =>
                {
                    b.Navigation("AnalisisResultados");

                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
